### PR TITLE
Add routeMinimum field to PHP SDK

### PR DESCRIPTION
**Pull request by Aman-Aalam**
feat!: Added routeMinimum field

# Fixes #

Added Recipient->routeMinimum field so that it appears in the response object.

### Checklist

- [X] I acknowledge that all my contributions will be made under the project's license
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have titled the PR appropriately
- [X] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by suitedjimster** [comment]
Not seeing code changes?
Also can we create a standard Response handler?

**Comment by Aman-Aalam** [comment]
> Not seeing code changes? Also can we create a standard Response handler?

@suitedjimster  Added the changed file (1). Sorry it got missed.

By a Standard Response Handler you mean something which passes down all the API response to the caller without needed specific response objects?

**Review by suitedjimster — APPROVED** [review]

**Comment by suitedjimster** [comment]
> 

@Sheikh-Aman correct. A caller that returns your formatted "ok" response, otherwise, it handles throwing the errors correctly instead of duplication those lines:
` if ($response['ok']) {
          return true;
      } else if ($response['errors']){
        throw new Exception\Standard($response['errors']);
      } else {
          throw new Exception\DownForMaintenance();
      }`

**Comment by Aman-Aalam** [comment]
@suitedjimster Thanks. We are dealing with similar features in a separate PR : https://github.com/PaymentRails/php-sdk/pull/21
Which will likely get there.

This one particularly is about adding `routeMinimum` attribute.
Please review that part

**Review by Yongyiw — APPROVED** [review]

**Review by Yongyiw — APPROVED** [review]

**Review by Yongyiw — APPROVED** [review]

**Review by barnett — APPROVED** [review]

**Review by sasha-trolley — APPROVED** [review]

**Pull request merged**
